### ISSUE TITLE
Estructura inicial del proyecto

### ISSUE THREAD

**Issue by Angatupyry** [Angatupyry/proyectoIntegrador#1]
@natmacira he creado el proyecto inicial. 
Tengo el nav dentro del header, ¿tiene sentido?, ¿cómo te parece que los nombres de las clases podrían escribirse?

**Comment by Natmacira** [comment]
Hola me parece genial el nav dentro del header !!

**Comment by Angatupyry** [comment]
¡Gracias, Nati!
